First components
gkmrm/FWT-Art-Gallery pull request #4
Opened 2023-07-03 10:15 UTC by gkmrm

### Сделаны компоненты:
1. buttons: 
    1) Стандартная кнопка
    2) Кнопка переключения темы (функцию пока не реализовал)
    3) Кнопка для скролла (функцию пока не реализовал)
2. Карточка
3. Грид для карточки
4. Ссылка(пока основанная на теге a, как буду подключать Роутер поменяю
5. Картинка для корректного отображения картины внутри карточки
___

### Дополнительно:
1. Иконки все собраны в папку svg, пропущены через svgomg
2. Шрифт добавлен к проекту локально, конвертирован в формат woff
3. Смог приручить alises и для проекта и для storybook
4. Начал офрмлять storybook, некоторые компоненты внутри отображаются без wrrapper'a  неккоректно, внутри приложения работают хорошо
6. Пытался в pixel perfect, есть проблема с отображением шрифта, он на 0.001-0.002px отличается, попробую прогнать шрифты через другой конвертер
7. Написал ещё несколько миксинов

2023-07-03 16:04 UTC, lightsout1993 requested changes

2023-07-03 16:04 UTC, lightsout1993 commented on src/components/CardGrid/CardGrid.tsx
> +    {arrayData.map((item) => (
это можно прокинуть в качестве children 
и таким образом можно обезличить компонент и назвать Grid
`{arrayData.map()`а это вынести на уровень выше

2023-07-03 16:04 UTC, lightsout1993 commented on src/components/Link/Link.tsx
раздели components (компоненты связанные с бизнес логикой, запросами и тд) и ui-components (компоненты относящиеся к ui, такие как Link, Select, Input, Button и тд)

2023-07-03 16:04 UTC, lightsout1993 commented on src/components/Link/Link.tsx
> +      rel='noreferrer'
{...other}

2023-07-03 16:04 UTC, lightsout1993 commented on src/components/Link/Link.tsx
> +      {children}
а children убрать

2023-07-03 16:04 UTC, lightsout1993 commented on src/components/ScrollButton/ScrollButton.module.scss
> +      background-color: #242222;
цвет в переменную

2023-07-04 13:31 UTC, gkmrm commented on src/components/Link/Link.tsx
> +      {children}
Убрал, начал ругаться eslint - [jsx-a11y/anchor-has-content](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/f0d2ddb65f21278ad29be43fb167a1092287b4b1/docs/rules/anchor-has-content.md)

2023-07-05 06:56 UTC, merged