Main page
gkmrm/FWT-Art-Gallery pull request #9
Opened 2023-07-10 06:48 UTC by gkmrm

### Сделаны компоненты:
1. Footer
2. Header (включая Burger menu)
3. Container
4. Navigation (тут Burger на читстом css, сделал его сначала, понял что получилось не очень, по этому сделал Burger menu внутри Header, этот компонент пока оставил, если нужно всё таки на чистом css использовать, жду апрув на использование моего меню внутри Header)
5. MainPage

___
### Сделана логика:
1. Переключения темы (указаны строковым типом), через context

___
### Дополнительно:
1) Переделал alises через craco, добавил автоматические импорты глобальных scss(появилась проблема, подробнее внизу)
2) Перераспределил папки - ui-components находятся теперь внутри components, файлы шрифтов перенес в assets
3) Написал ещё несколько миксинов

___
### Из проблемного:
0) Ещё на прошлой неделе очень много потратил времени на конфиг storybook, потмоу что он не в какую не хотел есть alises, но настроил через плагин.

1) Когда сделал автоматические импорты scss через craco, появилась проблема со storybook, в его конфиг файле main.ts, я пытался прокидывать эту же [additional data](https://spec-zone.ru/webpack~5/loaders/sass-loader#additionaldata), и просто модулем прокидывал, и внутри лоадера пытался прописать, использовал [addon styling](https://storybook.js.org/addons/@storybook/addon-styling), [preset scss](https://github.com/storybookjs/presets/tree/master/packages/preset-scss) вместо preset create react app -> все это не помогло, оставил закомментированные импорты в ui компонентах, пока не решу эту проблему. 

2) У меня есть правила из eslint, например: которые требуют [jsx-a11y/interactive-supports-focus](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/f0d2ddb65f21278ad29be43fb167a1092287b4b1/docs/rules/interactive-supports-focus.md) наличия tab-index у div, мне сейчас потратить время на изучение этого и подобных правил 'jsx-a11y' или не задерживаться и больше сил вложить в само приложение и изучение redux? А к этим правилам вернуться в коцне стажировки?

2023-07-11 14:26 UTC, lightsout1993 requested changes

2023-07-11 14:26 UTC, lightsout1993 commented on src/components/Header/Header.module.scss
> +  z-index: 9;
везде вынеси их, лучше их калькулируй через scss

2023-07-11 14:26 UTC, lightsout1993 commented on src/components/Header/Header.module.scss
> +    background-color: #0303034d;
rgba(, ) и сам цвет в переменную

2023-07-11 14:26 UTC, lightsout1993 commented on src/components/Header/Header.tsx
> +    : cx('header__menu', `header__menu_${theme}`);
`cx('header__menu', 'header__menu_${theme}', { header__menu_active:  isNavigationActive })` и в jsx

2023-07-11 14:26 UTC, lightsout1993 commented on src/components/Header/Header.tsx
> +            onKeyDown={() => setNavigationStatus(!isNavigationActive)}
`setNavigationStatus(!isNavigationActive)` - вынеси в метод toggle

2023-07-11 14:26 UTC, lightsout1993 commented on src/components/Header/Header.tsx
> +              [`header__button_active`]: isNavigationActive,
скобки убрать header__button_active

2023-07-11 14:26 UTC, lightsout1993 commented on src/components/Header/Header.tsx
> +          <div
role="presentation"

2023-07-11 14:26 UTC, lightsout1993 commented on src/components/Header/Header.tsx
> +        {isNavigationActive ? (
isNavigationActive &&

2023-07-11 14:26 UTC, lightsout1993 commented on src/components/Header/Header.tsx
> +          <div
тоже button

2023-07-11 14:26 UTC, lightsout1993 commented on src/components/Header/Header.tsx
> +  const [isNavigationActive, setNavigationStatus] = useState(false);
isOpen, setIsOpen

2023-07-11 14:26 UTC, lightsout1993 commented on src/components/ToggleTheme/ToggleTheme.tsx
> +  const onThemeChange = () =>
добавь логику сохранения в localStorage

2023-07-11 14:26 UTC, lightsout1993 commented on src/components/ui-components/Card/Card.tsx
> +  <div className={cx('card')} onClick={onClick} role='presentation'>
link

2023-07-11 14:26 UTC, lightsout1993 commented on src/hooks/ThemeConext/ThemeContext.ts
перенеси в папку context

2023-07-11 14:26 UTC, lightsout1993 commented on src/hooks/ThemeConext/ThemeContext.ts
> +const ThemeProvider = ThemeContext.Provider;
сделай это компонентом, и стейт из App забери сюда

2023-07-11 14:26 UTC, lightsout1993 commented on src/index.scss
>  @import './styles/variables';
убери

2023-07-11 14:26 UTC, lightsout1993 commented on src/styles/_variables.scss
> +$breakPointPC: 1280px;
breakpoint

2023-07-11 14:26 UTC, lightsout1993 commented on tsconfig.paths.json
> +      "@ui-components/*": ["src/components/ui-components/*"],
ui-components перенеси на уровень выше в src

2023-07-12 07:02 UTC, gkmrm commented on src/components/App/App.tsx
> +  const [theme, setTheme] = useState<ThemeTypes>('light');
Сделал компонент ThemeProviderComponent, не уверен в нейминге

2023-07-12 07:03 UTC, gkmrm commented on src/components/App/App.tsx
> +import { MainPage } from '../../pages/MainPage';
добавил

2023-07-12 07:50 UTC, gkmrm commented on src/components/Container/Container.tsx
> +export type TContainerProps = {
отнаследовался от React.HTMLAttributes<HTMLDivElement>, пытался убрать также className и если предположить , что я всё правильно сделал - тогда у меня ругается eslint [prop-types](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/prop-types.md)

2023-07-12 08:48 UTC, gkmrm commented on src/components/Footer/Footer.module.scss
> +      display: inline-flex;
ссылку целиком переносит, чтобы слова не разъединялись, другой способ найти?

2023-07-12 09:15 UTC, gkmrm commented on src/components/Header/Header.module.scss
> +      height: 200vh;
Ломалась вёрстка без них, сейчас подрекдактировал, заменил на min-height: 100%

2023-07-12 12:22 UTC, gkmrm commented on src/components/ui-components/Card/Card.tsx
> +  <div className={cx('card')} onClick={onClick} role='presentation'>
Обернул Card в компонент Link, в следующей ветке делаю роутинг, отредактирую компонент Link, и как сделаю вторую страницу - подумаю как правильнее логику карточки переиспользовать, делать два компонента для Артиста и Картины или всё попытаться сделать на Link

2023-07-17 13:20 UTC, merged